# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

ignored = [
  "github.com/loomnetwork/go-loom*",
  "github.com/loomnetwork/loomchain*",
  "github.com/miguelmota/go-solidity-sha3",
  "golang.org/x/crypto*",
  "google.golang.org/grpc*",
  "github.com/gogo/protobuf*",
  "github.com/hashicorp/go-plugin*",
  "github.com/spf13/cobra*",
  "github.com/spf13/pflag*",
  "github.com/ethereum/go-ethereum*",
  "github.com/go-kit/kit*",
  "github.com/grpc-ecosystem/go-grpc-prometheus*",
  "github.com/prometheus/client_golang/prometheus*",
  "github.com/certusone/yubihsm-go*",
  "github.com/jmhodges/levigo*", # can only build it with the right c packages
  "github.com/btcsuite/btcd*"
]

[[constraint]]
  name = "github.com/spf13/viper"
  version = "~1.0.0"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "=0.14.0"

[[constraint]]
  name = "github.com/btcsuite/btcutil"
  revision = "9e5f4b9a998d263e3ce9c56664a7816001ac8000"

[prune]
  go-tests = true
  unused-packages = true
